#
# Additional parameters
#

# Site wide favicon for browser and OS display
favicon:
  svg: favicon/favicon.svg
  png: favicon/favicon.png

imaging:
  sizestep: 25
  fallback_width: 660

modOpenIn:
  name: VSCodium
  protocol: vscodium
# fathomSiteID: ABCDEFG

render_hooks:
  link:
    errorLevel: warning
  fragments:
    errorLevel: ignore

giscus:
  enable: true
  repo: "Kariton/jaspers-it"
  repo_id: "R_kgDOMYPaxg"
  category: "giscus"
  category_id: "DIC_kwDOMYPaxs4ChFa0"
  mapping: "pathname"
  strict: true
  reactions_enabled: true
  emit_metadata: false
  input_position: "top"
  theme: "preferred_color_scheme"
  loading: "lazy"
