#####################################################################
#                            Build Stage                            #
#####################################################################
FROM hugomods/hugo:exts AS builder

ARG HUGO_ENV
ENV HUGO_ENV ${HUGO_ENV}
ARG HUGO_ENVIRONMENT
ENV HUGO_ENVIRONMENT ${HUGO_ENVIRONMENT}

COPY . /src
RUN hugo --gc --minify

# Generate pagefind index
RUN npm_config_yes=true npx pagefind

#####################################################################
#                              Publish                              #
#####################################################################
FROM alpine:latest

ARG HETZNER_SFTP_USERNAME
ENV HETZNER_SFTP_USERNAME ${HETZNER_SFTP_USERNAME}
ARG HETZNER_SFTP_SSH_KEY
ENV HETZNER_SFTP_SSH_KEY ${HETZNER_SFTP_SSH_KEY}
ARG HETZNER_SFTP_HOST
ENV HETZNER_SFTP_HOST ${HETZNER_SFTP_HOST}
ARG HETZNER_SFTP_DIRECTORY
ENV HETZNER_SFTP_DIRECTORY ${HETZNER_SFTP_DIRECTORY}

RUN apk add --update-cache \
        openssh \
        lftp \
    && rm -rf /var/cache/apk/*

RUN mkdir -p ~/.ssh &&\
    echo -e "${HETZNER_SFTP_SSH_KEY}" > ~/.ssh/id_ed25519  &&\
    chmod 600 ~/.ssh/id_ed25519 && \
    ssh-keyscan -p 22 -t ed25519 "${HETZNER_SFTP_HOST}" >> ~/.ssh/known_hosts

COPY --from=builder /src/public /public

RUN lftp -e " \
        set sftp:connect-program 'ssh -a -x -i ~/.ssh/id_ed25519'; \
        mirror -vv --no-empty-dirs --no-symlinks --delete --reverse ./public ${HETZNER_SFTP_DIRECTORY}; \
        bye \
        " -u "${HETZNER_SFTP_USERNAME}", sftp://${HETZNER_SFTP_HOST}
