on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  hetzner_webhost:
    runs-on: ubuntu-latest
    environment: "${{ github.ref_name == 'main' && 'production' || 'draft' }}-hetzner_webhost"
    steps:
      - name: Install lftp
        run: |
          sudo apt update
          sudo apt install -y lftp

      - name: Download public directory as artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.ref_name }}-public
          path: ./public

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 -t ed25519 "${HOST}" >> ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.HETZNER_SFTP_SSH_KEY }}
          HOST: ${{ secrets.HETZNER_SFTP_HOST }}

      - name: Deploy to Hetzner Webhosting
        run: |
          lftp -e " \
              set sftp:connect-program 'ssh -a -x -i ~/.ssh/id_ed25519'; \
              mirror -vv --no-empty-dirs --no-symlinks --delete --reverse ./public ${DIRECTORY}; \
              bye \
              " -u "${USERNAME}", sftp://${HOST}
        env:
          USERNAME: ${{ secrets.HETZNER_SFTP_USERNAME }}
          HOST: ${{ secrets.HETZNER_SFTP_HOST }}
          DIRECTORY: ${{ secrets.HETZNER_SFTP_DIRECTORY }}
