name: Hugo build

on:
  push:
    branches: ["main"]
    paths:
      - '.github/**'
      - 'assets/**'
      - 'config/**'
      - 'content/**'
      - 'layouts/**'
      - 'resources/**'
      - 'static/**'
      - 'themes/**'
      - 'package.json'
      - 'pagefind.yaml'
      - 'postcss.config.js'

  workflow_dispatch:

concurrency:
  group: "hugo"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.2
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create LFS file list
        run: git lfs ls-files --long | cut -d ' ' -f1 | sort > .lfs-assets-id

      - name: LFS Cache
        uses: actions/cache@v3
        with:
          path: .git/lfs/objects
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
          restore-keys: |
            ${{ runner.os }}-lfs

      - name: Git LFS Pull
        run: git lfs pull

      - name: Fetch resources directory from cache
        uses: actions/cache@v3
        with:
          path: resources
          key: ${{ runner.os }}-hugo-resources-directory-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-hugo-resources-directory  

      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify

      - name: Run pagefind
        run: npm_config_yes=true npx pagefind

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: ./public
          if-no-files-found: error
